# Usar imagem base completa do Python
FROM python:3.9

# Instalar dependências Python
RUN pip install --no-cache-dir pandas boto3

# Definir diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos do projeto para o container
COPY . /app

# Comando padrão para executar o script Python
CMD ["python", "script.py"]
